openapi: 3.0.0
info:
  title: Minesweeper AI API
  description: An API that uses an AI model to play Minesweeper
  version: 0.0.1
paths:
  /leastLikelyCell:
    post:
      summary: Get the least likely cell to contain a mine
      description: Given the current state of the Minesweeper board, the AI model will predict the cell that is least likely to contain a mine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Board"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                example: [3, 4]
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: "Invalid input data"
components:
  schemas:
    Board:
      type: object
      properties:
        height:
          type: integer
          example: 10
        width:
          type: integer
          example: 10
        board:
          type: array
          items:
            type: array
            items:
              type: object
              properties:
                isRevealed:
                  type: boolean
                  example: false
                adjacentMines:
                  type: integer
                  example: 0
