services:
  static_files:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost/health && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  model_api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost/health && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  reverse_proxy:
    build:
      context: ./reverse-proxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost/health && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      model_api:
        condition: service_healthy
      static_files:
        condition: service_healthy
networks:
  default:
    driver: bridge
